name: Build and Deploy Laravel API to Cloud Run

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Authenticate Docker with Artifact Registry
        run: gcloud auth configure-docker asia-southeast2-docker.pkg.dev

      - name: Build and push Docker image
        run: |
          echo "Building Docker image..."
          IMAGE="asia-southeast2-docker.pkg.dev/artoz-backend/artoz-ci-cd/artoz-server-laravel-ci-cd:latest"
          docker build -t $IMAGE .
          echo "Pushing Docker image to Artifact Registry..."
          docker push $IMAGE

      - name: Deploy to Cloud Run
        run: |
          echo "Deploying to Cloud Run..."
          gcloud run deploy artoz-server-laravel-ci-cd \
            --image "asia-southeast2-docker.pkg.dev/artoz-backend/artoz-ci-cd/artoz-server-laravel-ci-cd:latest" \
            --region asia-southeast2 \
            --platform managed \
            --allow-unauthenticated
