name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - prod # Trigger hanya untuk branch "prod"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Authenticate Docker with Artifact Registry
        run: gcloud auth configure-docker asia-southeast2-docker.pkg.dev

      - name: Build and push Docker image
        run: |
          IMAGE="asia-southeast2-docker.pkg.dev/artoz-backend/artoz/artoz-server-laravel:latest"
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy artoz-server-laravel \
            --image "asia-southeast2-docker.pkg.dev/artoz-backend/artoz/artoz-server-laravel:latest" \
            --region ${{ secrets.REGION }} \
            --platform managed \
            --allow-unauthenticated
